name: Test
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: Install ⚙️
        run: yarn install
      - name: Lint 💉
        run: yarn lint
      - name: Test 🛡️
        run: yarn test --coverage
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Build 🔧
        run: yarn build
